### ISSUE TITLE
Paragons have no sacrifices.

### ISSUE THREAD

**Issue by MrWomanStealer** [doombubbles/sacrifice-helper#1]
When creating a paragon the mod just spawns it in, without any sacrifices. (Tier 1 paragon)
But also the tier 5's and sacrificial tier 4's don't disappear. Only the tier 5 which you picked to upgrade changes.

**Comment by doombubbles** [comment]
Wanted to let you know I'm aware of this, but that fixing it requires not using the main Harmony Patch that the mod currently works on (thanks v32). I'd been meaning to do an internal revamp of this mod anyway, so that's what I'm planning to do.

**Comment by MrWomanStealer** [comment]
That's great to hear.
